services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: bus
      POSTGRES_PASSWORD: schedule
      POSTGRES_DB: travel_in_estonia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: